version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
  - index.html
  - favicon.ico
  - billgrant_resume.pdf
  - styles/*
  - images/*
  - dist/bundle.js
